openapi: 3.0.0
info:
  title: Sanctuary App API
  version: 1.0.0
  description: API for Sanctuary App integration with Zed and LiveKit
paths:
  /auth/login:
    post:
      summary: Authenticate user and return JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
  /user/profile:
    get:
      summary: Get user profile
      security:
      - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                type: object
  /livekit/token:
    get:
      summary: Get LiveKit token for voice/video session
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: string
      - name: sessionId
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: LiveKit token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /presence/{sessionId}:
    get:
      summary: Get list of active users in a session
      parameters:
      - name: sessionId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of active users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        userId:
                          type: string
                        username:
                          type: string
  /ai/companion/message:
    post:
      summary: Send a message to an AI companion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                companionId:
                  type: string
                message:
                  type: string
                context:
                  type: string
              required:
              - userId
              - companionId
              - message
      responses:
        '200':
          description: AI companion reply
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: string
                  emotion:
                    type: string
                  suggestions:
                    type: array
                    items:
                      type: string
  /ai/companion/code-review:
    post:
      summary: Submit code for AI review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fileContent:
                  type: string
                language:
                  type: string
                stylePreferences:
                  type: string
              required:
              - fileContent
              - language
      responses:
        '200':
          description: AI code review feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                  improvements:
                    type: array
                    items:
                      type: string
                  emotionalTone:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
